[package]
name = "mangasee"
version = "0.1.0"
authors = ["Muhammad Fadhlika <fadhlika@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
tanoshi-lib = {git = "https://github.com/faldez/tanoshi-lib", branch = "master"}
anyhow = "1"
ureq = "1"
scraper = "0.12"
chrono = "0.4"
serde = "*"
serde_urlencoded = "0.6"
serde_yaml="0.8"
