name: Build

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]
    paths:
      - extensions/**

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: rustup target add wasm32-wasi
      - name: Build
        run: |
          cargo build --release --target wasm32-wasi
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: extensions-wasm
          path: target/wasm32-wasi/release/*.wasm
  serialize:
    runs-on: ${{ matrix.os }}
    needs:
      - build-wasm
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            triple: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            triple: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            triple: aarch64-unknown-linux-gnu
          - os: macos-latest
            triple: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: extensions-wasm
          path: repo/library
      - name: Compile ${{ matrix.triple }}
        run: tanoshi-cli --path repo --target ${{ matrix.triple }} --remove-wasm true
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: extensions-${{ matrix.triple }}
          path: repo/library/*.tanoshi
  push:
    runs-on: ubuntu-latest
    needs:
      - build-wasm
      - serialize
    strategy:
      matrix:
        triple:
          - wasm
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: extensions-${{ matrix.triple }}
          path: repo/library
      - name: Setup
        run: cargo install tanoshi-cli --git https://github.com/faldez/tanoshi --branch llvm-dylib --features disable-compiler
        env:
          LLSM_SYS_110_PREFIX: ${{ env.LLVM_PATH }}
      - name: Generate index.json
        run: tanoshi-cli generate-json --path repo/library
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: repo
