name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone repo
        run: git clone https://github.com/faldez/tanoshi-extensions.git -b repo
      - name: Clear directory
        run: |
          cd repo
          rm -r *
      - name: Build
        run: |
          rustup target add wasm32-wasi
          cargo build --release --target wasm32-wasi
      - name: Generate index.json
        run: |
          cargo run --release generate_json
      - name: Commit files
        run: |
          cd repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "deploy"
      - name: Git Commit and Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: repo-linux
          force: true
          directory: repo-linux
