name: Publish

on:
  push:
    branches: [master]
    paths:
      - src/**
      - multisrc/**
      - ".github/workflows/publish.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Clone repo
        run: git clone https://github.com/faldez/tanoshi-extensions.git -b dist dist
      - run: npm install -g lerna
      - run: npm install
      - run: npm run build
      - run: npm run generate-json
      - name: Commit files
        run: |
          cd dist
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"
      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dist
          force: true
          directory: dist
