name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Generate index.json
        run: cargo run --release generate_json
      - name: Clone repo
        run: git clone https://github.com/faldez/tanoshi-extensions.git -b repo-windows  repo-windows 
      - name: Copy plugins
        run: mkdir -p library && cp target\release\*.dll repo-windows\library\
      - name: Commit files
        run: |
          cd repo-windows
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"\
          git add index.json library\*.dll
          git commit -m "auto commit"
      - name: Git Commit and Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: repo-windows
          force: true
          directory: repo-windows
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Generate index.json
        run: cargo run --release generate_json
      - name: Clone repo
        run: git clone https://github.com/faldez/tanoshi-extensions.git -b repo-macos repo-macos
      - name: Copy plugins
        run: mkdir -p library && cp target/release/*.dylib repo-macos/library/
      - name: Commit files
        run: |
          cd repo-macos
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"\
          git add index.json library/*.dylib
          git commit -m "auto commit"
      - name: Git Commit and Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: repo-macos
          force: true
          directory: repo-macos
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --release
      - name: Generate index.json
        run: cargo run --release generate_json
      - name: Clone repo
        run: git clone https://github.com/faldez/tanoshi-extensions.git -b repo-linux repo-linux
      - name: Copy plugins
        run: mkdir -p library && cp target/release/*.so repo-linux/library/
      - name: Commit files
        run: |
          cd repo-linux
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"\
          git add index.json library/*.so
          git commit -m "auto commit"
      - name: Git Commit and Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: repo-linux
          force: true
          directory: repo-linux
