name: Test

on:
  pull_request:
    paths:
      - src/**
      - multisrc/**
  push:
    branches: [master]
    paths:
      - ".github/workflows/test.yml"
      - src/**
      - multisrc/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: tanoshi-cli --version 0.5.0-beta.1
      - uses: actions/setup-node@v2
      - run: npm install -g lerna
      - run: npm install
      - run: npm run test
